baseURL: "mijux.github.io"
languageCode: "en-us"
title: "Mijux's blog"
theme: "github-style"

pygmentsCodeFences: true
pygmentsUseClasses: true

params:
  author: "Mijux"
  description: "Amateurs hack systems, professionals hack people."
  github: "Mijux"
  twitter: "MijuxDev"
  cyberdefenders: "Mijux"
  dockerhub: "mijuxdev"
#   facebook: "<your-facebook-username>"
#   linkedin: "<your-linkedin-username>"
#   instagram: "<your-instagram-username>"
#   tumblr: "<your-tumblr-username>"
  email: "mijux-dev@proton.me"
  url: "https://mijux.github.io"
  keywords: "blog, cyber, cybersecurity, cyberdefense, programming, coding, IT, security, portfolio, write-up, analytics"
  rss: true
  lastmod: true
  userStatusEmoji: "ğŸ›¡ï¸"
  favicon: "/images/avatar.png"
  location: "ğŸ¤– Cyberspace"

#  matomoServer: "<your-mamoto-server>"
#  matomoId: "<your-mamoto-id>"

  vinceServer: "analytics.nogg.ovh"
  vinceDataDomain: "mijux.github.io"

  avatar: "/images/avatar.png"
  headerIcon: "/images/avatar.png"

#  enableGitalk: true
#  params:
#    gitalk:
#      clientID: "Your client ID"
#      clientSecret: "Your client secret"
#      repo: "repo"
#      owner: "username"
#      admin: "username"
#      id: "location.pathname"
#      labels: "gitalk"
#      perPage: 15
#      pagerDirection: "last"
#      createIssueManually: true
#      distractionFreeMode: false

frontmatter:
  lastmod:
    - "lastmod"
    - ":fileModTime"
    - ":default"

markup:
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true


DefaultContentLanguage: "en"
languages:
  en:
    languageName: "English ğŸ‡ºğŸ‡¸"
    weight: 1
    params:
      locale: "en-US"
  fr:
    languageName: "FranÃ§ais ğŸ‡«ğŸ‡·"
    weight: 2
    params:
      locale: "fr-FR"
      description: "Les amateurs piratent les systÃ¨mes, les professionnels piratent les personnes."
